version: '3'

services:
  docker-mysql:
    image: mysql/mysql-server
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=counter_db
      - MYSQL_USER=bestuser
      - MYSQL_PASSWORD=bestuser
    ports:
      - 3306:3306

  app:
    image: counter2:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/database?autoReconnect=true&useSSL=false
    depends_on:
      - docker-mysql