version: '3.8'

services:
  docker-mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=counter_db
      - MYSQL_USER=bestuser
      - MYSQL_PASSWORD=bestuser
    ports:
      - 3307:3306
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d


  app:
    image: counter.jar:latest
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://docker-mysql:3306/counter_db?autoReconnect=true&useSSL=false
    depends_on:
      - docker-mysql